on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: deploy to cluster
      uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: build and push to docker
      uses: docker/build-push-action@v2
        repository: ${{ github.repository }}
        tags: ${{ github.sha }}