name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  okteto:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@@v2
    - name: Build & Push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: safernandez666/okteto
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}